{% set name = "pygod" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygod-{{ version }}.tar.gz
  sha256: 8b39b32c66524cf3eb72e4fefabe2a2b268fb8ab7e3d85cc258fc60ba5773f5a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=50.3.1
  run:
    - numpy >=1.19.4
    - networkx
    - python >=3.7
    - pytorch >=1.10.0
    - pytorch_geometric >=2.0.3
    - scikit-learn >=0.22.1
    - scipy >=1.5.2
    - setuptools >=50.3.1.post20201107

test:
  imports:
    - pygod
    - pygod.models
    - pygod.utils
  commands:
    - pip list | grep -E "{{ name }}\s+{{ version }}"
  requires:
    - pip
    - pytorch_cluster

about:
  home: https://pygod.org/
  dev_url: https://github.com/pygod-team/pygod/
  doc_url: https://docs.pygod.org/en/latest/
  summary: A Python Library for Graph Outlier Detection (Anomaly Detection)
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
