{% set name = "pygod" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygod-{{ version }}.tar.gz
  sha256: a9afd0db3a55b3ff20d24212cf85381db356456d6e21ba1f9687daf3619c5b36

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=38.6.0
  run:
    - numpy
    - networkx
    - python >={{ python_min }}
    - scikit-learn
    - scipy
    - setuptools
    # Not listed as dependencies but needed when importing base package
    - pytorch
    - pytorch_geometric >=2.3.0

test:
  imports:
    - pygod
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pygod.org/
  dev_url: https://github.com/pygod-team/pygod/
  doc_url: https://docs.pygod.org/en/latest/
  summary: A Python Library for Graph Outlier Detection (Anomaly Detection)
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
